### PR TITLE
Pybind11

### PR DESCRIPTION
**Pull request by sfarrens**
- Removed Boost requirements
- Changed bindings to Pybind11 syntax

### CODE REVIEW

**Comment by zaccharieramzi** [comment]
Since I understood this is almost done, I was looking at how we could compute the adjoints with the isap wavelets. Currently there is no easy way to do it with the bindings (even with this new approach) as there is no way to rotate the filters when calling the transform. I was wondering whether this PR was a good place to solve this issue.

**Comment by zaccharieramzi** [comment]
Similarly, I think it would be a good idea to have the ability to get rid of the coarse scale (like [here](https://github.com/CEA-COSMIC/ModOpt/tree/master/modopt/signal#L134) when setting the `coarse` arg to `False`) when performing the analysis (synthesis not possible afterwards).

**Comment by sfarrens** [comment]
With regards to your first point, I think it depends on how much needs to be changed to accommodate this feature. If it is significant then it is probably best left for a separate PR so as not to mix too many issues. If not, then I can probably add it to this PR.

For the second point I am not sure that this feature needs to be implemented at the binding level, and if not it's best to have a separate PR for this too.

**Comment by zaccharieramzi** [comment]
But at least for the first point, if we don;t want to do it in the bindings, we need to be able to access the filters to rotate them, which I think is not the case here right? I don't really know how easy it would be.

For the second point I see that in the current wrapper code, it is done when getting the filters so I don't think it would be possible to do it not at the binding level if we didn't have access to the filters.

**Pull request merged**
