### PR TITLE
Added paper ref

### PR DESCRIPTION
**Pull request by zaccharieramzi**
link to paper + bibtex entry

### CODE REVIEW

**Review by sfarrens — APPROVED** [review]

**Comment by zaccharieramzi** [comment]
@sfarrens I just don't know how to build the docs locally to test this

**Comment by sfarrens** [comment]
@zaccharieramzi do you mean the API docs? If so then, as far as I am aware, the `README.rst` is not included.

If you want to check what the readme will look like then you only need something that renders 
reStructuredText. I use an Atom plugin, but you could also try [restview](https://pypi.org/project/restview/).

If you just want to know how to build the API docs locally, then these are the steps (from the PySAP root directory):
```python
$ pip install -r doc/requirements.txt
$ sphinxdoc -p ./ -n pysap -o ./doc
$ cd doc
$ make raw-html
```

This will generate the HTML files in `doc/build/html/`.

**Comment by zaccharieramzi** [comment]
No I actually meant the readme. Which Atom plugin do you use?

**Comment by sfarrens** [comment]
I use [rst-preview-pandoc](https://atom.io/packages/rst-preview-pandoc), things don't render exactly as they do on GitHub, but at least you can see if there any issues.

**Comment by zaccharieramzi** [comment]
@sfarrens I think the travis build fail is not from my changes.

[This line](https://travis-ci.org/github/CEA-COSMIC/pysap/jobs/737957905#L1967) indicates that it has more to do with nibabel not supporting python 3.5 anymore (I think the `f'{string}'` syntax is not valid in 3.5).

**Comment by sfarrens** [comment]
@zaccharieramzi you are right. I am happy to merge this when you are.

**Comment by zaccharieramzi** [comment]
I think I am happy with it, so you can go for it

**Pull request merged**
