### PR TITLE
Updated docs

### PR DESCRIPTION
**Pull request by sfarrens**
- updated the content of the PySAP documentation
- added landing page for PySAP documentation
- updated basics example

### CODE REVIEW

**Comment by chaithyagr** [comment]
Rebasing and restarting the runs to test and also documentations

**Review by chaithyagr — APPROVED** [review]
LGTM. Had one minor issue. 
I guess if there are issues we can tackle it soon.

**Comment by chaithyagr** [comment]
@sfarrens seems like macOS had some issues

**Comment by sfarrens** [comment]
Yeah, I will have to investigate what is going on. The tests were running for over 2h, so something weird is happening.

**Comment by chaithyagr** [comment]
Perhaps it will be good to trigger a build at develop branch to see if this issue pertains to this pr. If the tests are already broken at mainline, the issue is different and not exactly a blocker for this PR right?

**Comment by sfarrens** [comment]
Yep, this is what I am planning to check.

**Comment by chaithyagr** [comment]
Merging now to handle the remaining issues in a different PR by @sfarrens 

Thank you @sfarrens for your contributions!

**Pull request merged**
