### PR TITLE
Version 0.0.5 release

### PR DESCRIPTION
**Pull request by sfarrens**
## Summary

- Set fixed versions for all package dependencies to have a more stable version of PySAP
- Dropped Circle and Travis CI 
- Set up CI using GitHub actions
- Added example tests to CI build
- Added PySAP Dockerfile with Jupyter notebook interface
- Updated conda `environment.yml` to facilitate local installation
- Updated `.readthedocs.yml` to use conda environment
- Added new MRI examples

### ModOpt and Plug-In Versions

- ModOpt v1.5.1
- PySAP-Astro v0.0.1
- PySAP-MRI v0.3.0

## PRs Included

- #146 
- #149
- #150
- #151 
- #152

### CODE REVIEW

**Review by philouc — COMMENTED** [review]
apt-get install -> apt install

**Comment by sfarrens** [comment]
> apt-get install -> apt install

@philouc are you referring to the Dockerfile?

**Comment by philouc** [comment]
> > apt-get install -> apt install
> 
> @philouc are you referring to the Dockerfile?

Yes (Lines 12 to 19) as far as I know!

**Comment by sfarrens** [comment]
> > > apt-getinstall -> apt install
> > 
> > 
> > @philouc are you referring to the Dockerfile?
> 
> Yes (Lines 12 to 19) as far as I know!

@philouc as far as I can see `apt-get` is the preference for use inside scripts and is what is [suggested for Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/). [According to this](https://askubuntu.com/questions/990823/apt-gives-unstable-cli-interface-warning) `apt` is preferred in the command line as it more verbose.

**Pull request merged**
